# Generated by Django 2.1.7 on 2019-11-14 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191114_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])]),
        ),
    ]
